### ISSUE TITLE
LogoStrip

### ISSUE THREAD

**Issue by SafeDuck** [acm-ucr/jm-products-website#42]
![image](https://github.com/user-attachments/assets/7eed0be7-122a-444e-8ec1-7b483f71f25f)

File is at `src/components/clamps/LogoStrip.jsx`

Images are in the `public/images/lineclamps/companies`

Use Image component from next.

**Comment by prodbysuj** [comment]
![screencapture-localhost-3000-line-clamps-2024-07-25-21_03_13](https://github.com/user-attachments/assets/3c0450ce-c0ba-4ef2-9d51-61c31d5e1302)
Completed making the tool bar component
