### ISSUE TITLE
Add Text to Banner ( Outsourcing )

### ISSUE THREAD

**Issue by JaviChip** [acm-ucr/jm-products-website#50]
<img width="841" alt="Screenshot 2024-07-13 at 7 58 49 PM" src="https://github.com/user-attachments/assets/84f563d8-088f-4098-88f6-be725534f8cd">

Hint: You should only edit one line and one file

**Comment by prodbysuj** [comment]
![screencapture-localhost-3000-outsourcing-2024-07-18-17_11_51](https://github.com/user-attachments/assets/f4c94f82-bfa9-455f-98ee-7bbff08725c3)

**Comment by prodbysuj** [comment]
This is what I have worked on, just to verify, what font should I be using for this
